Repository salesforce/bazel-ls-eclipse, pull requests merged in 2020-04, with the labels that each got.

#52 (#39) Publish p2 repo to GitHub pages
  .github/workflows/build.yml
Labels: cla:signed

#51 Fix file separator for win os
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/config/BazelEclipseProjectFactory.java
Labels: bug, cla:signed

#54 Separation properties files of initialization params and others plugin properties
  com.salesforce.b2eclipse.ui/src/main/java/com/salesforce/b2eclipse/ui/Config.java
  com.salesforce.b2eclipse.ui/src/main/resources/init_params.properties
  com.salesforce.b2eclipse.ui/src/main/resources/plugin.properties
Labels: cla:signed, enhancement

#55 Skip creating folder link if link already exist
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/config/BazelEclipseProjectFactory.java
Labels: bug, cla:signed

#57 Save bazel workspace root directory as preference
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/BazelJdtPlugin.java
Labels: bug, cla:signed

#58 #56 Add proper error handling
  README.md
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/config/BazelEclipseProjectFactory.java
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/config/ImportOrderResolver.java
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/model/BazelPackageInfo.java
Labels: cla:signed

#60 Update Assumptions section in the README
  README.md
Labels: cla:signed

#63 Remove .project files
  .project
  com.salesforce.b2eclipse.jdt.ls/.project
  com.salesforce.b2eclipse.repository/.project
  com.salesforce.b2eclipse.tests/.project
  com.salesforce.b2eclipse.ui/.project
Labels: cla:signed

#62 Make b2eclipse.jdt.ls as JDT LS extension
  com.salesforce.b2eclipse.jdt.ls/META-INF/MANIFEST.MF
  com.salesforce.b2eclipse.jdt.ls/com.salesforce.b2eclipse.jdt.ls.target
  com.salesforce.b2eclipse.jdt.ls/launch/jdt.ls.socket-stream.launch
  com.salesforce.b2eclipse.jdt.ls/plugin.xml
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/config/BazelEclipseProjectFactory.java
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/managers/B2EPreferncesManager.java
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/managers/BazelProjectImporter.java
  com.salesforce.b2eclipse.repository/category.xml
  com.salesforce.b2eclipse.tests/META-INF/MANIFEST.MF
  com.salesforce.b2eclipse.tests/src/main/java/com/salesforce/b2eclipse/BazelImportTest.java
  pom.xml
Labels: cla:signed, enhancement

#67 Set org.eclipse.jdt.ls.core version=0.0.0
  com.salesforce.b2eclipse.jdt.ls/com.salesforce.b2eclipse.jdt.ls.target
Labels: bug, cla:signed

#70 add org.eclipse.jdt.launching.macosx to launch config
  com.salesforce.b2eclipse.jdt.ls/launch/jdt.ls.socket-stream.launch
Labels: cla:signed

#71 Extract bundle resources to a cache
  com.salesforce.b2eclipse.jdt.ls/src/main/java/com/salesforce/b2eclipse/config/BazelAspectLocationImpl.java
  com.salesforce.b2eclipse.tests/pom.xml
Labels: cla:signed
